// constants.js
//    Defines constants useful for battleship game
// =============================================================================
//                            DO NOT EDIT THIS FILE
// =============================================================================
//      written by: Sean
//      edited by: Kristian Kostal
// #############################################################################

// battleship board side length
const BOARD_LEN = 6;
// describes image file paths
const EXPLOSION_IMG = './media/explosion.png', SPLASH_IMG = './media/splash.png';
// number of ships each player must place
const NUM_SHIPS = 10;
