# all known breeds
breeds = {
    "ABL": "American Bobtail Longhair",
    "ABS": "American Bobtail Shorthair",
    "ABY": "Abyssinian",
    "ACL": "American Curl Longhair",
    "ACS": "American Curl Shorthair",
    "AKE": "American Keuda (REFR only)",
    "ALC": "Asian Leopard Cat (REFR only)",
    "ALH": "Asian Longhair",
    "ALP": "Alpine Lynx (REFR only)",
    "ALX": "American Lynx (REFR only)",
    "AMB": "American Burmese (used in countries where European type is default)",
    "AMC": "American Miniature Cat (REFR only)",
    "AMS": "American Shorthair",
    "APD": "American Polydactyl (REFR only)",
    "APL": "Aphrodite Longhair/Shorthair",
    "ARM": "Arabian Mau",
    "ASN": "Asian (where LH and SH are not differentiated)",
    "ASH": "American Shorthair (in registries where ASS=Asian SH)",
    "ASL": "Asian Longhair (Tiffanie)",
    "ASS": "Asian Shorthair (in registries where ASH=American SH)",
    "AUM": "Australian Mist",
    "AWH": "American Wirehair (AMW sometimes used)",
    "AZT": "Aztek",
    "BAL": "Balinese",
    "BBC": "Bambino Curl (REFR only)",
    "BBO": "Bambino (REFR only)",
    "BBN": "Bambino (REFR only)",
    "BCT": "Bobcat (REFR only)",
    "BEN": "Bengal (BGL in REFR)",
    "BLH": "British Longhair",
    "BMB": "BamBob (REFR only)",
    "BML": "Burmilla (Burmilla Longhair)",
    "BOL": "Bombay Longhair (where recognised, it is “ALH n” elsewhere )",
    "BOM": "Bombay Shorthair (where longhaired version is not recognised)",
    "BOS": "Bombay Shorthair (where both LH and SH are recognised)",
    "BRA": "Bramble (REFR only)",
    "BRI": "British Shorthair",
    "BRL": "British Longhair",
    "BRX": "Bohemian Rex",
    "BSH": "British Shorthair (WCF use BSH for Brazilian Shorthair)",
    "BUA": "American Burmese (where both types are recognised, and where BUR = European type)",
    "BUR": "Burmese (the “default” type for the region = European type in Europe, American type in USA)",
    "BZS": "Brazilian Shorthair (REFR only)",
    "CAM": "Cashmere (Bengal Longhair)",
    "CEY": "Ceylon",
    "CHA": "Chartreux (CHS in WCF)",
    "CHQ": "Chinese Harlequin (REFR only)",
    "CHX": "Chartreux (REFR only, CHA used for Chausie)",
    "COP": "Copper (REFR only)",
    "COS": "Colourpoint Shorthair",
    "CRL": "Caracal (REFR only)",
    "CRX": "Cornish Rex",
    "CSH": "Colorpoint Shorthair (REFR only)",
    "CSP": "California Spangled (REFR only)",
    "CTL": "Curly Tail Cat (REFR only)",
    "CTO": "California Toyger (REFR only, TOG elsewhere)",
    "CTC": "Chinese Tank Cat (REFR only)",
    "CYM": "Cymric",
    "DLH": "Deutsche (German) Longhair",
    "DLX": "Desert Lynx (REFR only)",
    "DOM": "Domestic cat, no breed",
    "DOS": "Dossow (REFR only)",
    "DRX": "Devon Rex",
    "DSP": "Don Sphynx",
    "DWF": "Dwelf (REFR only)",
    "ELF": "Elf (REFR only)",
    "EUR": "European Shorthair",
    "EXO": "Exotic Shorthair",
    "FCT": "fishing Cat (REFR only)",
    "FEX": "Foldex (REFR only)",
    "GEN": "Genetta (REFR only)",
    "GLH": "German Longhair (REFR only, DLH elsewhere)",
    "GRX": "German Rex",
    "GTM": "Gao Taem (REFR only)",
    "HAV": "Havana Brown (US); Suffolk (UK)",
    "HCL": "Domestic (Household) cat, longhaired",
    "HCS": "Domestic (Household) cat, shorthaired",
    "HFD": "Highland Fold (REFR only)",
    "HLX": "Highland Lynx (REFR only)",
    "HPS": "Household Pet Shorthair (WCF)",
    "HPL": "Household Longhair (WCF)",
    "JBB": "JungleBob (REFR only)",
    "JBL": "Japanese Bobtail Longhair",
    "JBT": "Japanese Bobtail Shorthair",
    "JAG": "Jaguarundi Curl (REFR only)",
    "JAV": "Javanese (REFR only)",
    "JCL": "Jungle Curl (REFR only)",
    "JCT": "Jungle Cat (REFR only)",
    "JGR": "Jaguarette (REFR only)",
    "JLA": "Jungala (REFR only)",
    "JLX": "Jungle Lynx (REFR only)",
    "KAN": "Kanaani",
    "KAS": "Karelian Bobtail",
    "KBL": "Kurilean Bobtail Longhair",
    "KBS": "Kurilean Bobtail Shorthair",
    "KKH": "Celtic / European Shorthair",
    "KKL": "Kinkalow (REFR only)",
    "KMA": "Khao Manee (KMN in REFR, KAM in WCF)",
    "KOR": "Korat",
    "LMK": "Lambkin (REFR only)",
    "LAP": "LaPerm (REFR only)",
    "LPL": "La Perm Longhair",
    "LPS": "La Perm Shorthair",
    "LYK": "Lykoi",
    "MAN": "Manx (MNX in REFR)",
    "MAU": "Egyptian Mau",
    "MBT": "Mekong Bobtail",
    "MCO": "Maine Coon",
    "MDY": "Mandalay",
    "MHB": "Mohave Bob (REFR only)",
    "MIL": "Minuet Longhair",
    "MIS": "Minuet Shorthair",
    "MJC": "Mokave Jag Cat (REFR only)",
    "MJS": "Mojave Spotted (REFR only)",
    "MKT": "Meerkats (REFR only – a cat breed, not the wild species)",
    "MNL": "Munchkin, longhaired variety",
    "MNS": "Munchkin, shorthaired variety",
    "MUN": "Munchkin (REFR only)",
    "MSK": "Minksin (REFR only)",
    "MTN": "Mountain Bobs (REFR only)",
    "NAP": "Napoleon (REFR only – Minuet elsewhere)",
    "NEB": "Nebelung",
    "NBS": "Nebelung, shorthaired variant (if not recognised as RUS)",
    "NEM": "Neva Masquerade (- colourpoint SIB)",
    "NFO": "Norwegian Forest Cat",
    "OCI": "Ocicat",
    "OJA": "Ojos Azules (REFR only, extinct)",
    "OLH": "Oriental Longhair",
    "OSH": "Oriental Shorthair",
    "OWY": "Owyhee Bob (REFR only)",
    "PAN": "Pantherette (REFR only)",
    "PBL": "Pixie-Bob Longhair (sometimes PXL)",
    "PBS": "Pixie-Bob Shorthair (sometimes PXS)",
    "PEB": "Peterbald (PET in REFR)",
    "PER": "Persian",
    "POL": "Maine Coon Polydactyl",
    "PPK": "Puppykat (REFR only)",
    "RAG": "Ragdoll",
    "RGM": "Ragamuffin",
    "RUF": "Ruffle (REFR only)",
    "RUS": "Russian Shorthair (RBL is Russian Blue in REFR)",
    "SAF": "Safari (REFR only)",
    "SAR": "Sashkin Rex (REFR only)",
    "SAV": "Savannah",
    "SBI": "Birman LH (Sacred Birman, BIR in REFR)",
    "SBS": "Birman SH (Temple Cat)",
    "SCS": "Scottish Shorthair (straight eared, SSH in REFR)",
    "SCL": "Scottish Longhair (straight eared, SLH in REFR)",
    "SER": "Serval (REFR only)",
    "SFL": "Scottish Fold Longhair (Highland Fold)",
    "SFS": "Scottish Fold Shorthair",
    "SGT": "Serengeti (REFR only)",
    "SIA": "Siamese",
    "SIB": "Siberian",
    "SIB33": "Neva Masquerade",
    "SIN": "Singapura (SGP in REFR)",
    "SKO": "Skookum (REFR only)",
    "SNB": "Snowbob (REFR only)",
    "SNO": "Snowshoe (SNS in REFR)",
    "SOK": "Sokoke",
    "SOM": "Somali",
    "SPH": "Sphynx (SPX in REFR)",
    "SRL": "Selkirk Rex Longhair",
    "SRS": "Selkirk Rex Shorthair",
    "SRX": "Selkirk Rex, not known if longhair or shorthair",
    "SYL": "Seychellois Longhair",
    "SYS": "Seychellois Shorthair",
    "THA": "Thai",
    "TIF": "Tiffany (not Tiffany/Chantilly – extinct, or Tiffanie (ALH))",
    "TNB": "Tennessee Bobtail (REFR only)",
    "TIG": "Tigri (REFR only)",
    "TOB": "Toybob",
    "TOL": "Tonkinese Longhair (Tibetan)",
    "TOS": "Tonkinese Shorthair",
    "TOY": "Toyger (TOG also used)",
    "TSI": "Trad Siamese (REFR only)",
    "TUN": "Tundra (REFR only)",
    "TRX": "Tennessee Rex",
    "TUA": "Turkish Angora (TKA in REFR)",
    "TUV": "Turkish Van (TVN in REFR)",
    "UKL": "Ukrainian Levkoy",
    "URL": "Ural Rex Longhair",
    "URX": "Ural Rex Shorthair",
    "VIV": "Viverral (REFR only)",
    "VNW": "Vienna Woods (REFR only)",
    "XHL": "non-recognised hairless",
    "XSH": "Shorthaired hybrid / non-recognised shorthair",
    "XLH": "Longhaired hybrid / non-recognised longhair",
    "YKC": "York Chocolate",
}

# all country codes
countries = {"AF": "Afghanistan",
             "AL": "Albania",
             "DZ": "Algeria",
             "AS": "American Samoa",
             "AD": "Andorra",
             "AO": "Angola",
             "AI": "Anguilla",
             "AQ": "Antarctica",
             "AG": "Antigua and Barbuda",
             "AR": "Argentina",
             "AM": "Armenia",
             "AW": "Aruba",
             "AU": "Australia",
             "AT": "Austria",
             "AZ": "Azerbaijan",
             "BS": "Bahamas",
             "BH": "Bahrain",
             "BD": "Bangladesh",
             "BB": "Barbados",
             "BY": "Belarus",
             "BE": "Belgium",
             "BZ": "Belize",
             "BJ": "Benin",
             "BM": "Bermuda",
             "BT": "Bhutan",
             "BO": "Bolivia",
             "BA": "Bosnia and Herzegovina",
             "BW": "Botswana",
             "BR": "Brazil",
             "IO": "British Indian Ocean Territory",
             "VG": "British Virgin Islands",
             "BN": "Brunei",
             "BG": "Bulgaria",
             "BF": "Burkina Faso",
             "BI": "Burundi",
             "KH": "Cambodia",
             "CM": "Cameroon",
             "CA": "Canada",
             "CV": "Cape Verde",
             "KY": "Cayman Islands",
             "CF": "Central African Republic",
             "TD": "Chad",
             "CL": "Chile",
             "CN": "China",
             "CX": "Christmas Island",
             "CC": "Cocos Islands",
             "CO": "Colombia",
             "KM": "Comoros",
             "CK": "Cook Islands",
             "CR": "Costa Rica",
             "HR": "Croatia",
             "CU": "Cuba",
             "CW": "Curacao",
             "CY": "Cyprus",
             "CZ": "Czech Republic",
             "CD": "Democratic Republic of the Congo",
             "DK": "Denmark",
             "DJ": "Djibouti",
             "DM": "Dominica",
             "DO": "Dominican Republic",
             "TL": "East Timor",
             "EC": "Ecuador",
             "EG": "Egypt",
             "SV": "El Salvador",
             "GQ": "Equatorial Guinea",
             "ER": "Eritrea",
             "EE": "Estonia",
             "ET": "Ethiopia",
             "FK": "Falkland Islands",
             "FO": "Faroe Islands",
             "FJ": "Fiji",
             "FI": "Finland",
             "FR": "France",
             "PF": "French Polynesia",
             "GA": "Gabon",
             "GM": "Gambia",
             "GE": "Georgia",
             "DE": "Germany",
             "GH": "Ghana",
             "GI": "Gibraltar",
             "GR": "Greece",
             "GL": "Greenland",
             "GD": "Grenada",
             "GU": "Guam",
             "GT": "Guatemala",
             "GG": "Guernsey",
             "GN": "Guinea",
             "GW": "Guinea-Bissau",
             "GY": "Guyana",
             "HT": "Haiti",
             "HN": "Honduras",
             "HK": "Hong Kong",
             "HU": "Hungary",
             "IS": "Iceland",
             "IN": "India",
             "ID": "Indonesia",
             "IR": "Iran",
             "IQ": "Iraq",
             "IE": "Ireland",
             "IM": "Isle of Man",
             "IL": "Israel",
             "IT": "Italy",
             "CI": "Ivory Coast",
             "JM": "Jamaica",
             "JP": "Japan",
             "JE": "Jersey",
             "JO": "Jordan",
             "KZ": "Kazakhstan",
             "KE": "Kenya",
             "KI": "Kiribati",
             "XK": "Kosovo",
             "KW": "Kuwait",
             "KG": "Kyrgyzstan",
             "LA": "Laos",
             "LV": "Latvia",
             "LB": "Lebanon",
             "LS": "Lesotho",
             "LR": "Liberia",
             "LY": "Libya",
             "LI": "Liechtenstein",
             "LT": "Lithuania",
             "LU": "Luxembourg",
             "MO": "Macau",
             "MK": "Macedonia",
             "MG": "Madagascar",
             "MW": "Malawi",
             "MY": "Malaysia",
             "MV": "Maldives",
             "ML": "Mali",
             "MT": "Malta",
             "MH": "Marshall Islands",
             "MR": "Mauritania",
             "MU": "Mauritius",
             "YT": "Mayotte",
             "MX": "Mexico",
             "FM": "Micronesia",
             "MD": "Moldova",
             "MC": "Monaco",
             "MN": "Mongolia",
             "ME": "Montenegro",
             "MS": "Montserrat",
             "MA": "Morocco",
             "MZ": "Mozambique",
             "MM": "Myanmar",
             "NA": "Namibia",
             "NR": "Nauru",
             "NP": "Nepal",
             "NL": "Netherlands",
             "AN": "Netherlands Antilles",
             "NC": "New Caledonia",
             "NZ": "New Zealand",
             "NI": "Nicaragua",
             "NE": "Niger",
             "NG": "Nigeria",
             "NU": "Niue",
             "KP": "North Korea",
             "MP": "Northern Mariana Islands",
             "NO": "Norway",
             "OM": "Oman",
             "PK": "Pakistan",
             "PW": "Palau",
             "PS": "Palestine",
             "PA": "Panama",
             "PG": "Papua New Guinea",
             "PY": "Paraguay",
             "PE": "Peru",
             "PH": "Philippines",
             "PN": "Pitcairn",
             "PL": "Poland",
             "PT": "Portugal",
             "PR": "Puerto Rico",
             "QA": "Qatar",
             "CG": "Republic of the Congo",
             "RE": "Reunion",
             "RO": "Romania",
             "RU": "Russia",
             "RW": "Rwanda",
             "BL": "Saint Barthelemy",
             "SH": "Saint Helena",
             "KN": "Saint Kitts and Nevis",
             "LC": "Saint Lucia",
             "MF": "Saint Martin",
             "PM": "Saint Pierre and Miquelon",
             "VC": "Saint Vincent and the Grenadines",
             "WS": "Samoa",
             "SM": "San Marino",
             "ST": "Sao Tome and Principe",
             "SA": "Saudi Arabia",
             "SN": "Senegal",
             "RS": "Serbia",
             "SC": "Seychelles",
             "SL": "Sierra Leone",
             "SG": "Singapore",
             "SX": "Sint Maarten",
             "SK": "Slovakia",
             "SI": "Slovenia",
             "SB": "Solomon Islands",
             "SO": "Somalia",
             "ZA": "South Africa",
             "KR": "South Korea",
             "SS": "South Sudan",
             "ES": "Spain",
             "LK": "Sri Lanka",
             "SD": "Sudan",
             "SR": "Suriname",
             "SJ": "Svalbard and Jan Mayen",
             "SZ": "Swaziland",
             "SE": "Sweden",
             "CH": "Switzerland",
             "SY": "Syria",
             "TW": "Taiwan",
             "TJ": "Tajikistan",
             "TZ": "Tanzania",
             "TH": "Thailand",
             "TG": "Togo",
             "TK": "Tokelau",
             "TO": "Tonga",
             "TT": "Trinidad and Tobago",
             "TN": "Tunisia",
             "TR": "Turkey",
             "TM": "Turkmenistan",
             "TC": "Turks and Caicos Islands",
             "TV": "Tuvalu",
             "VI": "U.S. Virgin Islands",
             "UG": "Uganda",
             "UA": "Ukraine",
             "AE": "United Arab Emirates",
             "GB": "United Kingdom",
             "US": "United States",
             "UY": "Uruguay",
             "UZ": "Uzbekistan",
             "VU": "Vanuatu",
             "VA": "Vatican",
             "VE": "Venezuela",
             "VN": "Vietnam",
             "WF": "Wallis and Futuna",
             "EH": "Western Sahara",
             "YE": "Yemen",
             "ZM": "Zambia",
             "ZW": "Zimbabwe"
             }

# all colors codes defined
colors = {
    "a": "Blue",
    "b": "Chocolate",
    "c": "Lilac",
    "d": "Red",
    "e": "Cream",
    "f": "Black tortie",
    "g": "Blue tortie",
    "h": "Chocolate tortie",
    "j": "Lilac tortie",
    "m": "Dilute modifier together with dilute colours (caramel = am, cm, gm, jm, pm, rm / apricot = em)",
    "n": "Black (seal in Himalayan-patterned cats, ruddy in Abyssinians and Somalis",
    "o": "Cinnamon (sorrel in Abyssinians)",
    "p": "Fawn",
    "q": "Cinnamon (sorrel) tortie",
    "r": "Fawn tortie",
    "s": "Silver, smoke",
    "t": "Amber, light amber for NFO, charcoal for BEN and SAV",
    "u": "Sunshine",
    "w": "White",
    "x": "Indicates an unrecognized colour",
    "y": "Golden",
    "z": "Russet"
}
