apiVersion: apps/v1
kind: Deployment
metadata:
  name: pprerko-projekt-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: pprerko-projekt-backend-label
  template:
    metadata:
      labels:
        pod: pprerko-projekt-backend-label
    spec:
      containers:
        - name: pprerko-projekt-backend-container
          image: xrericha/projekt-backend
          imagePullPolicy: Always
          ports:
            - name: webapi-port
              containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "0.1"
            limits:
              memory: "128Mi"
              cpu: "0.3"
          env:
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: mongodb_uri
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
