apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: ClusterIP
  externalTrafficPolicy: null  # <== vymaže konfliktné polia, 
                               # platné len pre typ LoadBalancer
  ipFamilyPolicy: null
  ipFamilies: null