/*
 * Projekt Api
 *
 * Projekt management
 *
 * API version: 1.0.0
 * Contact: aa@bb.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	dbservice "projekt-backend/db-service"
	router "projekt-backend/router"
)

func main() {
	log.Printf("Server started")

	dbservice.Connect()
	defer dbservice.Disconnect()

	router := router.NewRouter()

	log.Fatal(router.Run(":8080"))
}
