/* tslint:disable */
/* eslint-disable */
/**
 * Projekt Api
 * Projekt management
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: aa@bb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

