/*
 * Projekt Api
 *
 * Projekt management
 *
 * API version: 1.0.0
 * Contact: aa@bb.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Ambulance struct {

	// Id of the ambulance
	Id string `json:"id" bson:"Id"`

	// Human readable display name of the ambulance
	Name string `json:"name,omitempty" bson:"Name,omitempty"`

	// Name of the doctor
	DoctorName string `json:"doctorName,omitempty" bson:"DoctorName,omitempty"`

	// Where it's at
	Location string `json:"location,omitempty" bson:"Location, omitempty"`
}
