/*
 * Projekt Api
 *
 * Projekt management
 *
 * API version: 1.0.0
 * Contact: aa@bb.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"
)

type MedicalAppointment struct {

	// Unique id of the entry
	Id string `json:"id" bson:"Id"`

	// Name of patient
	PatientName string `json:"patientName,omitempty" bson:"PatientName,omitempty"`

	// Name of ambulance where the appointment happened
	AmbulanceId string `json:"ambulanceId,omitempty" bson:"AmbulanceId,omitempty"`

	// Type of the appointment
	Type string `json:"type,omitempty" bson:"Type,omitempty"`

	// date
	DateTime time.Time `json:"dateTime,omitempty" bson:"DateTime,omitempty"`

	// cost paid in euros
	Cost int32 `json:"cost,omitempty" bson:"Cost,omitempty"`

	// who paid for the appointment
	PaidBy string `json:"paidBy,omitempty" bson:"PaidBy,omitempty"`
}
