apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: manual # hodnota sa musí zhodovať so storageClassName v manifeste pre persistent volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi