apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:                  # zoznam manifestov - zdrojov,
                            # ktoré sú súčasťou tejto aplikácie
- deployment.yaml
- service.yaml
- webcomponent.yaml

commonLabels:               # značky priradené všetkým zdrojom tejto aplikácie
  app: pprerko-ambulance-frontend