apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: wac-hospital
  namespace: ingress-nginx
spec:
  controller: k8s.io/ingress-nginx   # <== priraďuje triedu "wac-hospital" konkrétnemu radiču