  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  namespace: wac-hospital

  secretGenerator:
    - name: mongodb-secret
      type: Opaque
      literals:
        - mongo-root-username=mongo-user
        - mongo-root-password=mongo-password
      options:
        disableNameSuffixHash: true